// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkplaceHealth.Api.Data;

#nullable disable

namespace WorkplaceHealth.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816110048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("WorkplaceHealth.Api.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("WorkplaceHealth.Api.Models.DiskReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Drive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FreeGb")
                        .HasColumnType("REAL");

                    b.Property<double>("FreePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("HealthReportId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalGb")
                        .HasColumnType("REAL");

                    b.Property<double>("UsedGb")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("HealthReportId");

                    b.ToTable("DiskReports");
                });

            modelBuilder.Entity("WorkplaceHealth.Api.Models.HealthReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvailableMemoryGb")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuLogicalProcessors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpuName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CpuUsagePercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentBuild")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MemoryUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("PendingUpdateCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RegistryCheckSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalMemoryGb")
                        .HasColumnType("REAL");

                    b.Property<bool>("UpdateCheckSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowsDisplayVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsUpdateServiceStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("HealthReports");
                });

            modelBuilder.Entity("WorkplaceHealth.Api.Models.ServiceReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HealthReportId");

                    b.ToTable("ServiceReports");
                });

            modelBuilder.Entity("WorkplaceHealth.Api.Models.DiskReport", b =>
                {
                    b.HasOne("WorkplaceHealth.Api.Models.HealthReport", "HealthReport")
                        .WithMany("Disks")
                        .HasForeignKey("HealthReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthReport");
                });

            modelBuilder.Entity("WorkplaceHealth.Api.Models.HealthReport", b =>
                {
                    b.HasOne("WorkplaceHealth.Api.Models.Device", "Device")
                        .WithMany("HealthReports")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WorkplaceHealth.Api.Models.ServiceReport", b =>
                {
                    b.HasOne("WorkplaceHealth.Api.Models.HealthReport", "HealthReport")
                        .WithMany("Services")
                        .HasForeignKey("HealthReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthReport");
                });

            modelBuilder.Entity("WorkplaceHealth.Api.Models.Device", b =>
                {
                    b.Navigation("HealthReports");
                });

            modelBuilder.Entity("WorkplaceHealth.Api.Models.HealthReport", b =>
                {
                    b.Navigation("Disks");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
